### PR TITLE
Make sure json schemas are installed by setup.py

### PR DESCRIPTION
**Pull request by chmeliik**
Signed-off-by: Adam Cmiel <acmiel@redhat.com>

Maintainers will complete the following section:
- [x] Commit messages are descriptive enough
- [x] "Signed-off-by:" line is present in each commit
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [x] Pull request includes link to an osbs-docs PR for user documentation updates

### CODE REVIEW

**Comment by MartinBasti** [comment]
Please rebase so we will if RPMs are build fine in copr

**Comment by MartinBasti** [comment]
Shall we also update this section in specfile?
```
%ghost %config(noreplace) %{_datadir}/osbs/orchestrator_customize.json
%ghost %config(noreplace) %{_datadir}/osbs/prod_customize.json
%ghost %config(noreplace) %{_datadir}/osbs/worker_customize.json
```

**Comment by chmeliik** [comment]
> Shall we also update this section in specfile?

@MartinBasti what exactly does that do? The "noreplace" part makes me think it marks that file as something that should not be replaced during a `dnf upgrade` - probably not what we want

**Comment by athos-ribeiro** [comment]
That's right. The files are ghosted because they are not being shipped by the package, but if they are there, they are owned by the package. Configuration files should not be replaced by new releases: we do not want to override user configurations. That is not true for **most** OSBS json files though. with exception for the *_customize.json files there, we usually want to overwrite these JSON files with plugin order (or schemas) on upgrades.

**Comment by athos-ribeiro** [comment]
Although, it would be nice to be explicit in the .spec file that we want to package everything under the schema dirs. Maybe adding sth like `%{datadir}/osbs/schemas/*.json` to the files section

**Comment by chmeliik** [comment]
@athos-ribeiro the schema does not go in /usr/share/osbs though, it goes in /usr/lib/python*/site-packages/osbs*. That's already in the spec as `%{python3_sitelib}/osbs*`

**Pull request merged**
