### PR TITLE
pass params to download_remote_sources plugin

### PR DESCRIPTION
**Pull request by rcerven**
* OSBS-8472

Signed-off-by: Robert Cerven <rcerven@redhat.com>

Maintainers will complete the following section:
- [x] Commit messages are descriptive enough
- [x] "Signed-off-by:" line is present in each commit
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [x] Pull request includes link to an osbs-docs PR for user documentation updates

### CODE REVIEW

**Comment by athos-ribeiro** [comment]
Waiving docs PR: this is already covered in the docs

**Comment by rcerven** [comment]
test depends on https://github.com/containerbuildsystem/osbs-client/pull/924

**Comment by athos-ribeiro** [comment]
#924 merged. Can you rebase your changes on master?

**Comment by rcerven** [comment]
rn updated: pass params to download_remote_sources plugin

**Pull request merged**
