### PR TITLE
Adjust the pre-build Flatpak plugins

### PR DESCRIPTION
**Pull request by owtaylor**
atomic-reactor is being changed to use the 'resolve_composes' plugin
for Flatpaks, instead of having a separate 'resolve_module_compose',
and to add a new 'flatpak_update_dockerfile' plugin that runs after
'resolve_composes'.
    
The 'resolve_composes' plugin is moved up a bit in the sequence of
orchestrator plugins so that 'flatpak_update_dockerfile' can set the
release label before bump_release runs. As far as I can tell, it should
work as well in the new location as the old location.

See https://github.com/containerbuildsystem/atomic-reactor/pull/1373

Maintainers will complete the following section:
- [x] Commit messages are descriptive enough
- [x] "Signed-off-by:" line is present in each commit
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [x] Pull request includes link to an osbs-docs PR for user documentation updates

### CODE REVIEW

**Comment by MartinBasti** [comment]
Please resolve conflicts

**Comment by rcerven** [comment]
bump_release should run before add_labels_in_dockerfile

also because it is now reserving builds in koji, it should also run before resolve_compose which might take a while

**Comment by owtaylor** [comment]
> bump_release should run before add_labels_in_dockerfile

That's the case with this patch set - unless I'm missing something I didn't change that.

> also because it is now reserving builds in koji, it should also run before resolve_compose which might take a while

The dependency chain is that flatpak_update_dockerfile now sets the release tag based on the results of resolve_compose. So, that's why the patch switches things to do bump_release after resolve_compose. Can you explain the rationale about timing a bit more? Does Koji time-out reservations?

**Comment by MartinBasti** [comment]
Release notes:
> - Flatpak plugins we rearranged to better support inheriting parent composes

**Pull request merged**
