### PR TITLE
Better validation errors reporting

### PR DESCRIPTION
**Pull request by SalatskySal**
# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [x] Pull request has a link to an osbs-docs PR for user documentation updates

### CODE REVIEW

**Comment by chmeliik** [comment]
If you want to test atomic-reactor with these changes, run test.sh in the atomic-reactor repo like this:
```shell
OS=fedora OS_VERSION=29 PYTHON_VERSION=2 \
OSBS_CLIENT_REPO=https://github.com/SalatskySal/osbs-client \
OSBS_CLIENT_BRANCH=osbs-8518 ./test.sh
```
And pro tip (in case you don't already know this trick): after tests start running, you can cancel them and run them like this:
```shell
podman exec -ti atomic-reactor-fedora-29-py2 pytest tests/ --stepwise
```
^ this means tests will always start from the last failure

**Comment by SalatskySal** [comment]
> If you want to test atomic-reactor with these changes, run test.sh in the atomic-reactor repo like this:
> 
> ```shell
> OS=fedora OS_VERSION=29 PYTHON_VERSION=2 \
> OSBS_CLIENT_REPO=https://github.com/SalatskySal/osbs-client \
> OSBS_CLIENT_BRANCH=osbs-8518 ./test.sh
> ```
> 
> And pro tip (in case you don't already know this trick): after tests start running, you can cancel them and run them like this:
> 
> ```shell
> podman exec -ti atomic-reactor-fedora-29-py2 pytest tests/ --stepwise
> ```
> 
> ^ this means tests will always start from the last failure

Thanks for the information :+1:

**Comment by chmeliik** [comment]
@SalatskySal please rebase, looks like master has had some changes in the container.json schema which are required for atomic-reactor unit tests

**Comment by MartinBasti** [comment]
RN: - Improved schema validation error messages

**Pull request merged**
