### PR TITLE
add `openetelemetry_info` to `user_params`

### PR DESCRIPTION
**Pull request by hjmodi**
# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [n/a] JSON/YAML configuration changes are updated in the relevant schema
- [n/a] Changes to metadata also update the documentation for the metadata
- [n/a] Pull request has a link to an osbs-docs PR for user documentation updates

### CODE REVIEW

**Comment by mkosiarc** [comment]
@rcerven @hjmodi Do we need to update the docs?

**Comment by mkosiarc** [comment]
@hjmodi I have the same question here as in atomic-reactor PR regarding the commit messages

**Comment by rcerven** [comment]
> @rcerven @hjmodi Do we need to update the docs?

we can add that otel_url https://github.com/containerbuildsystem/osbs-client/blob/master/docs/configuration_file.md and I'd say that is all we need to document

**Comment by hjmodi** [comment]
@mkosiarc @rcerven updated commit messages and added documentation for config change.

**Review by mkosiarc — APPROVED** [review]

**Pull request merged**
