### PR TITLE
inputs: delete old arrangements

### PR DESCRIPTION
**Pull request by mlangsdorf**
part of osbs-6573

Now that all the code that uses arrangements 1-5 is gone, delete
the JSON files that defined them.

Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>

### CODE REVIEW

**Comment by MartinBasti** [comment]
IMHO `prod_inner.json` should be unused and removed too.

**Comment by MartinBasti** [comment]
Hmm, but it is actually used as `DEFAULT_INNER_TEMPLATE` but only in tests.

**Comment by mlangsdorf** [comment]
Tests updated, prod*json removed.

**Comment by mlangsdorf** [comment]
Not adding anything to release notes because this is housekeeping for a feature already added to release notes.

**Pull request merged**
