### PR TITLE
Embed content sets information in built container images

### PR DESCRIPTION
**Pull request by rcerven**
* CLOUDBLD-764

Signed-off-by: Robert Cerven <rcerven@redhat.com>

# Maintainers will complete the following section

- [ ] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [ ] Pull request has a link to an osbs-docs PR for user documentation updates

### CODE REVIEW

**Comment by athos-ribeiro** [comment]
Also, I believe we will want a docs PR for this one.

**Comment by rcerven** [comment]
sure plugin can run before add_dockerfile

**Comment by rcerven** [comment]
@athos-ribeiro  added doc to https://github.com/containerbuildsystem/atomic-reactor/pull/1441/files
not sure where else should we add it

**Comment by athos-ribeiro** [comment]
@rcerven It would be nice to have an entry in osbs-docs saying this file is generated with content sets data

**Comment by rcerven** [comment]
rn updated: - Embed content sets information in built container images, run new `pre_add_content_sets` plugin

**Pull request merged**
