### PR TITLE
remove clusters and can_orchestrate occurrences

### PR DESCRIPTION
**Pull request by rcerven**
* CLOUDBLD-9135

Signed-off-by: Robert Cerven <rcerven@redhat.com>

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [n/a] JSON/YAML configuration changes are updated in the relevant schema
- [n/a] Changes to metadata also update the documentation for the metadata
- [x] Pull request has a link to an osbs-docs PR for user documentation updates

### CODE REVIEW

**Review by tkdchen — APPROVED** [review]

**Review by mkosiarc — APPROVED** [review]

**Comment by mkosiarc** [comment]
@rcerven Will you be opening a PR to osbs-docs as well?

**Comment by rcerven** [comment]
> @rcerven Will you be opening a PR to osbs-docs as well?

yeah I should

**Comment by rcerven** [comment]
> > @rcerven Will you be opening a PR to osbs-docs as well?
> 
> yeah I should

https://github.com/containerbuildsystem/osbs-docs/pull/215

**Comment by rcerven** [comment]
rn updated

**Pull request merged**
