### PR TITLE
run new koji_delegate prebuild plugin

### PR DESCRIPTION
**Pull request by rcerven**
* OSBS-8150

Signed-off-by: Robert Cerven <rcerven@redhat.com>

Maintainers will complete the following section:
- [x] Commit messages are descriptive enough
- [x] "Signed-off-by:" line is present in each commit
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [x] Pull request includes link to an osbs-docs PR for user documentation updates

### CODE REVIEW

**Comment by athos-ribeiro** [comment]
Do we want to document this feature somehow?I see no section describing the relation between autorebuilds and koji in osbs-docs

**Comment by rcerven** [comment]
there isn't much to document, since task used for autorebuilds ins't described anywhere,
all we need is just announcement to users

**Comment by rcerven** [comment]
atomic-reactor counterpart https://github.com/containerbuildsystem/atomic-reactor/pull/1280

**Comment by rcerven** [comment]
rn updated

**Pull request merged**
